config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/not_found", to: "welcome#not_found"
  get "/register", to: "users#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :items
  resources :cart
  resources :categories, only: [:show]
  resources :orders_items

  resources :users do
    resources :orders
  end

  namespace :admin do
    resources :categories
    resources :items
    resources :orders
  end

  resources :suppliers, path: "", param: :slug
  namespace :suppliers, as: :supplier, path: "/:slug" do
    resources :categories
    resources :items
    resources :orders
		resources :users
  end
end

app/views/partials/_admin_footer.html.erb
<footer id="footer" class="footer navbar-fixed-bottom">
  <div class="row">
    <div class="col-md-12">
      <h4>Administrator Controls</h4>
      <%= link_to('Manage Customer Orders', admin_orders_path, class: "btn btn-lg btn-default orders") %>
      <%= link_to "Manage Categories", admin_categories_path, class: "btn btn-lg btn-default" %>
      <%= link_to "Manage Items", admin_items_path, class: "btn btn-lg btn-default" %>
    </div>
  </div>
</footer>

app/views/partials/_categories_class.html.erb
<% item.categories.each do |category| %>
  <%= category.name %>
<% end %>

app/views/partials/_edit_item.html.erb
<div class="form-horizontal">

<%= form_for [@supplier, @item], url: supplier_item_path(@supplier.slug, @item), method: :put, :html => { multipart: true } do |f| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
        <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %> </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, "Title", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :title, placeholder: "New Item Name", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, "Item Description", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_area :description, placeholder: "New Item Description", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, "Item Price", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :price, placeholder: "New Item Price", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :quantity, "Quantity Available", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :quantity, placeholder: "Quantity Available", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :location, "Current Location", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :location, placeholder: "Item location", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :unit_size, "Unit Size", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :unit_size, placeholder: "Unit Size", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :unit_weight, "Unit Weight", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :unit_weight, placeholder: "Unit Weight", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :retired, "Retire Item?", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
      <%= f.check_box :retired %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :available, "Item Not Currently Available?", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
      <%= f.check_box :available %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :shippable, "Item Not Shippable?", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
      <%= f.check_box :shippable %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :image, "Image", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.file_field :image %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-7">
        <%= f.hidden_field :supplier_id, :value => @supplier.id %>
      </div>
    </div>

    <div id="form-group">
      <%= f.label :category, "Category", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%   @categories.each do |category| %>
        <%=  f.label :category_list, category.name, class: "checkbox-inline" %>
        <%=  check_box(:category_list, "categories", {:multiple => true}, category.name, nil) %>
        <% end %>
      </div>
    </div>

    <div class="form-group text-right">
    <div class="col-sm-9">
      <%= f.submit "Save", class: "btn btn-lg btn-default" %>
    </div>
    </div>
  <% end %>
</div>

app/views/partials/_footer.html.erb
<footer id="footer" class="footer navbar-fixed-bottom">
  <div class="row">
    <div class="col-md-12">
      <h4>Administrator Controls</h4>
      <%= link_to('Manage Customer Orders', admin_orders_path, class: "btn btn-lg btn-default orders") %>
      <%= link_to "Manage Categories", admin_categories_path, class: "btn btn-lg btn-default" %>
      <%= link_to "Manage Items", admin_items_path, class: "btn btn-lg btn-default" %>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<div id="header-box">
  <div class="row">
    <div id="logo" class="col-md-1">
      <!-- airlift logo -->
    </div>

    <div id="restaurant_name" class="col-md-7">
      <h1><%= link_to("Airlift", root_url )%></h1>
      <h4>Emergency Supplies Delivered Fast</h4>
    </div>

    <div id="user_nav" class="col-md-3 text-right">
      <div class="row">

        <% if current_user %>

         <% if !current_user.supplier? %>
            <div class="row">
              <div class="col-sm-12">
                <h4>Welcome, <%= current_user.fullname %></h4>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-6">
                <%= link_to('My Order History', user_orders_path(current_user), class: "btn btn-default logout") %>
              </div>
              <div class="col-sm-6">
                <%= link_to('Logout', logout_path, :method => :get, class: "btn btn-default logout") %>
              </div>
            </div>
          <% else %>
            <div class="col-sm-12">
              <%= link_to('Logout', logout_path, :method => :get, class: "btn btn-default logout") %>
            </div>
          <% end %>

        <% else %>
          <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal">Log In</button>
          <div class="modal fade login-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-md">
              <div class="login-modal-content">
                <%= render partial: "./partials/login" %>
              </div>
            </div>
          </div>
          <button type="button" class="btn btn-link btn-default register" data-toggle="modal" data-target=".reg-modal">Register</button>
          <div class="modal fade reg-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="register-modal-content">
                <%= render partial: "./partials/register_form" %>
              </div>
            </div>
          </div>
        <% end %>

      </div>
    </div>
    <div class="col-md-1">
    </div>
  </div>

  <div class="row search-nav">
    <div class="col-md-1">
    </div>

    <div id="search-bar" class="col-md-6">
      <div class="row">
        <div class="col-sm-9">
          <%= form_tag(items_path, method: "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "search supplies",size: 102, class: "form-control" %>
        </div>
        <div class="col-sm-3">
          <%= submit_tag "Search", name: nil, class: "btn btn-default search" %>
        <% end %>
        </div>
      </div>
    </div>

    <div id="all-supplies" class="col-md-2 text-right">
      <%= link_to "View All Supplies", items_path, class: "btn btn-default view-items" %>
    </div>

    <div id="cart" class="col-md-2 text-right">
      <% if !current_user.present? || !current_user.supplier? %>
				<i class="fa fa-shopping-cart fa-2x"></i><%= link_to " Items: #{@cart.count_total}", cart_path(cart_id = @cart) %>
			<% else %>
      	<%= link_to "View Profile", supplier_path(current_user.supplier_slug(current_user.id)), class: "btn btn-default profile" %>
			<% end %>
    </div>

    <div class="col-md-1">
    </div>
  </div>
</div>

app/views/partials/_item_index.html.erb
<div class="row col-md-12">
  <div class="row col-md-1">
  </div>
  <div class="row col-md-10">
    <div class="create text-right">
      <button type="button" class="btn btn-lg btn-default create" data-toggle="modal" data-target=".reg-modal">Create New Item</button>
         <div class="modal fade reg-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
           <div class="modal-dialog modal-lg">
             <div class="modal-content">
              <%= render partial: "./partials/item_form" %>
             </div>
           </div>
         </div>
    </div>
    <table class="table">
      <tr><th>Item</th><th></th><th>Description</th><th>Location</th><th>Price</th><th>Quantity</th><th>Unit Size</th><th>Unit Weight</th><th>Status</th><th>Availability</th><th>Shipping</th><th></th></tr>
      <% @supplier.items.each do |item| %>
      <div class="<%= item.title.split.join %>">
      <tr>
        <td>
          <%= link_to item.title, item_path(item) %>
        </td>
        <td>
          <%= image_tag item.image.url(:thumb) %>
        </td>
        <td>
          <%= item.description %>
        </td>
        <td>
          <%= item.location %>
        </td>
        <td>
          <%= number_to_currency(item.format_price) %>
        </td>
        <td>
          <%= item.quantity %>
        </td>
        <td>
          <%= item.unit_size %>
        </td>
        <td>
          <%= item.unit_weight %>
        </td>
        <td>
          <%= item.item_retired %>
        </td>
        <td>
          <%= item.item_available %>
        </td>
        <td>
          <%= item.item_shippable %>
        </td>
        <td>
          <%= link_to "Edit Item", edit_supplier_item_path(@supplier.slug, item) %>
        </td>
      </tr>
      </div>
      <% end %>
    </table>
  </div>
  <div class="row col-md-1">
  </div>
</div>

app/views/partials/_item_index_item_details.html.erb
<div id="item-info">
  <button type="button" class="btn btn-link view-btn" data-toggle="modal" data-target=".<%= item.title.split.join %>">View More Info</button></br>
    <h5>
      <%= item.title %>
    </h5>
    <p>
      <%= number_to_currency(item.format_price) %>
    </p>
    <% if !current_user || current_user && !current_user.supplier? %>
      <%= button_to "Add to Cart", cart_index_path(item_id: item), class: "btn btn-default" %>
    <% end %>
</div>

app/views/partials/_login.html.erb
<div id="session" class="form-horizontal login-modal-info">
  <%= form_for(:session, url: login_path) do |f| %>
      <div class="form-group">
        <%= f.label :email, class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control logout" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, class: "col-sm-4 control-label" %>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="col-sm-2 form-group modal-login-button">
          <%= f.submit "Log In", class: "btn btn-default login" %>
        </div>
      </div>
    <% end %>
    <div id="login-modal-register">
  <button type="button" class="btn btn-link btn-default" data-toggle="modal" data-target=".reg-modal">Not Registered?</button>
    </div>
</div>

app/views/partials/_register_form.html.erb
<div class="form-horizontal reg-form">
  <%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fullname, "Full Name", class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :fullname, placeholder: "Enter Full Name", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :display_name, "Display Name", class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :display_name, placeholder: "Enter Display Name", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.email_field :email, placeholder: "Enter Email", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.password_field :password, placeholder: "Enter Password", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-3 control-label" %>
    <div class="col-sm-8">
      <%= f.password_field :password_confirmation, placeholder: "Enter Password Confirmation", class: "form-control" %>
    </div>
  </div>

  <div class="action col-sm-8 register-signup-button">
    <%= f.submit "Sign Up", class: "btn btn-lg btn-default text-right" %>
  </div>

  <% end %>
</div>

app/views/partials/_sidebar.html.erb
<div class="filters sidebar col-md-3">
 <h2>All Items</h2>
  <h4>Filter by Category</h4>
  <%= render partial: "partials/categories" %>
  <h4>Filter by Supplier</h4>
  <%= render partial: "partials/supplier_list" %>
</div>

app/views/partials/_supplier_admin_edit_form.html.erb
<div class="form-horizontal reg-form">
	<%= form_for [@supplier, user], url: supplier_user_path(@supplier.slug, user), method: :put do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fullname, "Full Name", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :fullname, placeholder: "Enter Full Name", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :display_name, "Display Name", class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :display_name, placeholder: "Enter Display Name", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-5">
      <%= f.email_field :email, placeholder: "Enter Email", class: "form-control" %>
    </div>
  </div>

	<% if @supplier.valid_supplier_admins? %>
		<div class="form-group">
  	  <%= f.label :role, class: "col-sm-2 control-label" %>
    	<div class="col-sm-5">
				<%= f.select(:role, [['Admin', "supplier"],["User", "default"]])  %>
    	</div>
		</div>
	<% end %>


	<div class="action col-sm-7 text-right">
		<%= f.submit "Update", class: "btn btn-lg btn-default text-right" %>
  </div>
<% end %>

app/views/partials/_supplier_edit_info_form.html.erb
<div class="form-horizontal">
	<%= form_for [@supplier], url: supplier_path(@supplier.slug), method: :patch do |f| %>	
		<% if @supplier.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@supplier.errors.count, "error") %> prohibited this item from being saved:</h2>
        <ul>
          <% @supplier.errors.full_messages.each do |message| %>
            <li><%= message %> </li>
          <% end %>
        </ul>
      </div>
		<% end %>

		<div class="form-group">
      <%= f.label :name, "Supplier Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :name, placeholder: "Supplier Name", class: "form-control" %>
      </div>
		</div>

		<div class="form-group">
      <%= f.label :description, "Supplier Description", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_area :description, placeholder: "Supplier Description", class: "form-control" %>
      </div>
		</div>  

		<div class="form-group text-right">
			<div class="col-sm-9">
				<%= f.submit "Update", class: "btn btn-lg btn-default" %>
			</div>
		</div>
	<% end  %>
</div>

app/views/partials/_supplier_footer.html.erb
<footer id="footer" class="footer navbar-fixed-bottom">
  <div class="row">
    <div class="col-md-12">
      <h4>Supplier Controls</h4>
      <%= link_to("View Account Details", admin_orders_path, class: "btn btn-lg btn-default orders") %>
      <%= link_to "Manage Customer Orders", admin_categories_path, class: "btn btn-lg btn-default" %>
      <%= link_to "Manage Items", admin_items_path, class: "btn btn-lg btn-default" %>
    </div>
  </div>
</footer>

app/views/partials/_supplier_list.html.erb
<div class="supplier_list">
    <% current_suppliers.each do |supplier| %>
      <label>
      <div id="supplier-checkbox"><%= check_box(:current_suppliers, supplier.slug,{multipart: true},  supplier.slug, nil) %>
          <%= supplier.name  %>
        </label>
        </div>
    <% end  %>
</div>