config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/not_found", to: "welcome#not_found"
  get "/register", to: "users#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :items
  resources :cart
  resources :categories, only: [:show]
  resources :orders_items

  resources :users do
    resources :orders
  end

  namespace :admin do
    resources :categories
    resources :items
    resources :orders
  end

  resources :suppliers, path: "", param: :slug
  namespace :suppliers, as: :supplier, path: "/:slug" do
    resources :categories
    resources :items
    resources :orders
		resources :users
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :description, presence: true
  validates :name, uniqueness: true
  has_many :item_categories
  has_many :items, through: :item_categories
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < AdminController
    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end

    def create
      category = Category.new(category_params)
      if category.save
        flash[:notice] = "New category successfully created!"
        redirect_to admin_categories_path
      else
        flash[:error] = "Unable to create category"
        redirect_to new_admin_category_path
      end
    end
    
    # def edit
    #   @category = Category.find(params[:id])
    # end

    def update
      @category = Category.find(params[:id])
      @category.update(category_params)
      if @category.save
        redirect_to admin_categories_path
      else
        render "admin/categories/edit"
      end
    end

    def destroy
      category = Category.find(params[:id])
      category.destroy
      redirect_to admin_categories_path
    end

    private

    def category_params
      params.require(:category).permit(:name, :description)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @listing = @category.items.all
  end
end

app/views/admin/categories/_form.html.erb
<div class="form-horizontal">
  <%= form_for(@category, url: admin_categories_path, method: :post) do |f| %>
    <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
        <li><%= message %> </li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, "Category Name", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_field :name, placeholder: "New Category Name", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, "Category Description", class: "col-sm-2 control-label" %>
      <div class="col-sm-7">
        <%= f.text_area :description, placeholder: "New Category Description", class: "form-control" %>
      </div>
    </div>

    <div class="action col-sm-9 text-right">
      <%= f.submit "Save", class: "btn btn-lg btn-default" %>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<div class="container">
  <h2>Edit a Category</h2>
  <%= render 'admin/categories/form' %>
</div>

app/views/admin/categories/index.html.erb
<div id="categories">

  <h2>Manage Categories </h2>

  <div class="create text-right">
    <%= link_to "Create New Category", new_admin_category_path, class: "btn btn-lg btn-default create" %>
  </div>

  <table class="table">
    <% @categories.each do |category| %>
    <tr>
      <td>
        <%= category.name %>
      </td>
      <td>
        <%= category.description %>
      </td>
      <td>
        <%= link_to "Edit", edit_admin_category_path(category.id), as: category.id %>
      </td>
      <td>
        <%= link_to "Delete", admin_category_path(category.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% end %>
  </table>

</div>

app/views/admin/categories/new.html.erb
<div class="container">
  <h2>Create New Category</h2>
  <%= render 'admin/categories/form' %>
</div>