config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/not_found", to: "welcome#not_found"
  get "/register", to: "users#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  resources :items
  resources :cart
  resources :categories, only: [:show]
  resources :orders_items

  resources :users do
    resources :orders
  end

  namespace :admin do
    resources :categories
    resources :items
    resources :orders
  end

  resources :suppliers, path: "", param: :slug
  namespace :suppliers, as: :supplier, path: "/:slug" do
    resources :categories
    resources :items
    resources :orders
		resources :users
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :status, presence: true
  validates :total, presence: true
  has_many :orders_items
  has_many :items, through: :orders_items
  has_many :addresses

  def self.status_counts(status_type)
    group(:status).having(status: status_type).count
  end

  def self.id_for(slug)
    Supplier.find_by(slug: slug).id
  end

  def change_status(commit)
    if commit == "Cancel Order"
      update(status: "cancelled")
    else commit == "Mark as Shipped"
      update(status: "completed")
    end
  end

  def self.get_supplier_orders_by_status(params)
    supplier_orders = self.get_supplier_orders(params)
    supplier_orders.flatten.group_by { |order| order.status }
  end

  def self.get_supplier_orders(params)
    items = Item.where(supplier_id: self.id_for(params[:slug]))
    items.map do |item|
      Order.joins(:orders_items).where(orders_items: { item_id: item.id })
    end.flatten.uniq
  end

  def self.get_order_and_items(id)
    self.includes(:orders_items).find(id)
  end

  def get_user(order)
    User.find(order.addresses.where(address_type: "billing").first.user_id)
  end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	validates :name, presence: true
	validates :description, presence: true
	has_many :items
  has_many :supplier_admins
  has_many :users, through: :supplier_admins

	before_update :update_slug

	def update_slug
		self.slug = name.parameterize
	end

	def find_user_admins
		supplier_admins.map { |supplier_admin| User.find_by(id: supplier_admin.user_id) }
	end

	def valid_supplier_admins?
		supplier_admins.count > 1 
	end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < AdminController
    include AdminOrdersHelper
    def index
      @orders = { ordered: Order.ordered,
                  paid: Order.paid,
                  completed: Order.completed,
                  cancelled: Order.cancelled
                }
      @all_orders = Order.all
    end

    def show
      set_order
      @user = User.find(@order.user_id)
    end

    def update
      change_status
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    authorize! :read, current_user.id
    @orders = current_user.orders
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def new
  end

  def create
    @order = Order.create(
                          status: "ordered",
                          total: @cart.total * 100,
                          user_id: current_user.id
                          )
    items = Item.find(@cart.data.keys)
    @line_items = items.map do |item|
      OrdersItem.create(
                        order_id: @order.id,
                        item_id: item.id,
                        quantity: @cart.data[item.id.to_s],
                        subtotal: item.price * @cart.data[item.id.to_s]
                        )
    end
    session[:cart] = nil
    redirect_to user_order_path(current_user, @order)
  end
end

app/controllers/suppliers/items_controller.rb
class Suppliers::ItemsController < SuppliersController
  before_action :supplier_authorization

  include SupplierItemsHelper
  def index
		@supplier = Supplier.where(slug: params[:slug]).includes(:items).take
		@item = Item.new
		get_all_categories
  end

  def new
    @supplier = Supplier.find_by(slug: params[:slug])
	 	@item = @supplier.items.new
    get_all_categories
  end

  def create
		@supplier = Supplier.find_by(slug: params[:slug])
		@item = @supplier.items.new(supplier_item_params)
    if category_list_nil?
      flash[:errors] = "You must select at least one category when creating a new item! Duh!"
      redirect_to :back
		elsif @item.save
      @item.add_categories_to_item(params[:category_list][:categories])
			flash[:success] = "Item successfully saved"
      redirect_to supplier_items_path(@supplier.slug)
		else
			flash[:error] = "Item not saved"
      redirect_to :back
    end
  end

  def edit
    @supplier = Supplier.where(slug: params[:slug]).includes(:items).take
    @item = @supplier.items.where(id: params[:id]).take
    @categories = Category.all
  end

  def update
    @supplier = Supplier.where(slug: params[:slug]).includes(:items).take
    item = @supplier.items.where(id: params[:id]).take
    if category_list_nil?
      flash[:errors] = "Please reassign your item to at least one category "
      redirect_to :back
    else
      item.add_categories_to_item(params[:category_list][:categories])
      item.update(supplier_item_params)
      flash[:success] = "Item successfully updated"
      redirect_to supplier_items_path(@supplier.slug)
    end
  end

	private

  def supplier_authorization
    redirect_to not_found_path if !current_user || current_user.supplier_slug(current_user.id) != params[:slug]
  end

	def supplier_item_params
		params.require(:item).permit(:title,
																 :description,
																 :price,
                                 :location,
																 :retired,
																 :supplier_id,
																 :quantity,
                                 :unit_size,
                                 :unit_weight,
                                 :shippable,
                                 :available,
                                 :image)
	end
end

app/controllers/suppliers/orders_controller.rb
class Suppliers::OrdersController < SuppliersController
  before_action :supplier_authorization

  def index
    @orders = Order.get_supplier_orders_by_status(params)
  end

  def show
    @order = Order.get_order_and_items(params[:id])
    @user = @order.get_user(@order)
    @shipping_address = @user.get_shipping_address(@user)
  end

  def update
    @order = Order.get_order_and_items(params[:id])
    @order.change_status(params[:commit])
    redirect_to supplier_orders_path
  end

  private

  def supplier_authorization
    redirect_to not_found_path if !current_user || current_user.supplier_slug(current_user.id) != params[:slug]
  end

end

app/controllers/suppliers/users_controller.rb
class Suppliers::UsersController < SuppliersController
	include SupplierUsersHelper
	def update
		@user =  User.find(params[:id])
		role = params[:user][:role]
		@supplier_admin = SupplierAdmin.find_by(user_id: @user.id)
		if @user.update(supplier_admin_params) && role == "supplier"
			flash[:success] = "User successfully updated"
			redirect_to supplier_path(@user.supplier_slug(@user.id))
		elsif role == "default"
			@supplier_admin.delete
			redirect_to :back
		else
			flash[:errors] = "User could not be updated"
			redirect_to :back
		end
	end

	private

	def supplier_admin_params
		params.require(:user).permit(:fullname,
																 :email,
																 :role) 
	end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController

  def show
    @supplier = Supplier.where(slug: params[:slug]).includes(:items).take
		@user = User.new
	end

	def update
			@supplier = Supplier.find_by(slug: params[:slug])
	  	if @supplier.update(supplier_params) || @user.update(supplier_admin_params)
				flash[:success] = "Supplier successfully updated."
				redirect_to supplier_path(@supplier.slug)
			else
				flash[:error] = "Supplier could not be updated."
				redirect_to :back
			end
	end

	private

	def supplier_params
		params.require(:supplier).permit(:name,
																		 :description,
																		 :user )
	end

  def supplier_authorization
    redirect_to not_found_path if !current_user || current_user.supplier_slug(current_user.id) != params[:slug]
  end
end

app/views/suppliers/orders/_cancelled.html.erb
<div roll="tabpanel" id="status-cancelled" class="tab-pane fade">
  <h3>Cancelled Orders
    <% if @orders["cancelled"] %>
      (<%= @orders["cancelled"].count %>)
    <% end %>
  </h3>

  <% if @orders["cancelled"] %>
    <table class="table">
      <% @orders["cancelled"].each do |order| %>
      <tr>
        <td>
          <%= link_to "Order# #{order[:id]}: ", supplier_order_path(id: order[:id]) %>
          <%= order.created_at.strftime("Submitted at: %b %d, %Y %H:%M") %>
        </td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>
      There are no cancelled orders to display.
    </p>
  <% end %>
</div>

app/views/suppliers/orders/_delivery_method.html.erb
<% if @shipping_address %>
  <h5>Shipping Address:</h5>
    <p>
      <%= @shipping_address.line_one %></br>
      <%= @shipping_address.line_two %></br>
      <%= @shipping_address.city %></br>
      <%= @shipping_address.state %></br>
      <%= @shipping_address.postal_code %></br>
      <%= @shipping_address.country %>
    </p>
<% else %>
  <h5>Delivery Method:</h5>
    <p>
      Pick-up
    </p>
<% end %>

app/views/suppliers/orders/_ordered.html.erb
<div roll="tabpanel" id="status-ordered" class="tab-pane fade in active">
  <h3>Pending Orders
    <% if @orders["ordered"] %>
      (<%= @orders["ordered"].count %>)
    <% end %>
  </h3>

  <% if @orders["ordered"] %>
    <table class="table">
      <% @orders["ordered"].each do |order| %>
      <tr>
        <td>
          <%= link_to "Order# #{order[:id]}: ", supplier_order_path(id: order[:id]) %>
          <%= order.created_at.strftime("Submitted at: %b %d, %Y %H:%M") %>
        </td>
        <td class="text-right">
          <%= form_tag(supplier_order_path(id: order[:id]), method: :put) do %>
            <%= submit_tag("Mark as Shipped", class: "btn btn-default") %>
          <% end %>
        </td>
        <td class="text-right">
          <%= form_tag(supplier_order_path(id: order[:id]), method: :put) do %>
            <%= submit_tag("Cancel Order", class: "btn btn-default") %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>
      There are no new orders to display.
    </p>
  <% end %>
</div>

app/views/suppliers/orders/_shipped.html.erb
<div roll="tabpanel" id="status-shipped" class="tab-pane fade">
  <h3>Shipped Orders
    <% if @orders["completed"] %>
      (<%= @orders["completed"].count %>)
    <% end %>
  </h3>

  <% if @orders["completed"] %>
    <table class="table">
      <% @orders["completed"].each do |order| %>
      <tr>
        <td>
          <%= link_to "Order# #{order[:id]}: ", supplier_order_path(id: order[:id]) %>
          <%= order.created_at.strftime("Submitted at: %b %d, %Y %H:%M") %>
        </td>
      </tr>
      <% end %>
    </table>
  <% else %>
    <p>
      There are no shipped orders to display.
    </p>
  <% end %>
  </div>

app/views/suppliers/orders/index.html.erb
<div id="orders">

  <h2>Manage Orders</h2>

  <ul id="order-tabs" class="nav nav-pills nav-justified" role="tab-list">
    <li role="presentation" class="active"><a href="#status-ordered" data-toggle="tab">Open</a></li>
    <li role="presentation"><a href="#status-shipped" data-toggle="tab">Shipped</a></li>
    <li role="presentation"><a href="#status-cancelled" data-toggle="tab">Cancelled</a></li>
  </ul>

  <div id="tab-content" class="tab-content">
      <%= render partial: 'ordered' %>
      <%= render partial: 'shipped' %>
      <%= render partial: 'cancelled' %>
  </div>

</div>

app/views/suppliers/orders/show.html.erb
<div id="status">
  <h4>Customer Order</h4>
  <h5>Customer Name:<h5>
    <p><%= @user.fullname %></p>
  <%= render "delivery_method" %>
  <h5></h5>

  <p>email: <%= @user.email %> </p>
  <p><%= @order.created_at.strftime("Submitted at: %b %d, %Y %H:%M")%></p>
  <p>
    Status: <%= @order.status %>
    <% if @order.status == "completed" || @order.status == "cancelled" %>
    <%= " - #{time_ago_in_words(@order.updated_at)} ago" %>
    <% end %>
  </p>
</div>

<h5>Order Details</h5>
<table id="ordertable" class="table">
  <thead>
    <tr>
      <th>Item</th><th>Quantity</th><th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @order.orders_items.each do |order_item|%>
    <tr>
      <td><%= link_to order_item.item.title, item_path(order_item.item) %></td>
      <td><%= order_item.quantity %></td>
      <td><%= number_to_currency(order_item.subtotal.to_f / 100.00) %></td>
    </tr>
    <% end %>
    <tr><td>Order Total: </td><td/><td><%= number_to_currency(@order.total.to_f / 100.00) %></td></tr>
  </tbody>
</table>